import Sidebar from "@/components/global/Sidebar";
import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "Admin",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`bg-gradient-to-br from-black via-gray-900 to-black text-white`}>
            <main className="main flex  gap-10 h-screen overflow-hidden ">

                <div className="w-full max-w-fit">
                    <Sidebar />
                </div>

                <div className="flex-1 h-full w-full">

                    {children}
                </div>
            </main>
        </div>
    );
}
